- app/models/audio_event.rb
It was missing the most crucial field - the one that made adding in the
tagging relation all worth it!
> Fix audio event tagging

- app/views/sites/_harvest.yml.haml
Leaving the utc_offset invalid reduces the chances that invalid data will be ingested and forces the harvester to sanity check timezone offsets.
> Updated harvest.yml with notes and safer defaults

- app/controllers/analysis_controller.rb
- spec/acceptance/analysis_spec.rb
Suffixing units to the end of the name is the standard for our site.
> Changed analysis results 'model' size attribute to size_bytes

- lib/modules/filter/comparison.rb
- lib/modules/filter/subset.rb
- lib/modules/filter/validate.rb
- spec/acceptance/audio_events_spec.rb
> validate filter values

- Gemfile
- app/controllers/application_controller.rb
- app/models/audio_event.rb
- spec/models/audio_event_spec.rb
> exclude deleted annotations from csv download

- lib/modules/access/by_permission.rb
- spec/lib/filter/query_spec.rb
> ensures admin filter api also respects the project filter for site permissions

- app/controllers/application_controller.rb
- app/controllers/audio_recordings_controller.rb
- app/controllers/media_controller.rb
- app/models/ability.rb
- app/models/audio_recording.rb
- app/models/range_request.rb
- config/routes.rb
- spec/acceptance/media_spec.rb
- spec/helpers/acceptance_spec_helper.rb
- spec/models/audio_recording_spec.rb
- spec/routing/audio_recordings_routing_spec.rb
- spec/routing/media_routing_spec.rb
Closes #353
Extends the Media controller so that original audio files can be downloaded. Currently limited to harvester or admin only (as enabling this generally could be expensive in terms of bandwidth).
Also:
- Supports range requests for original audio
- Adds two helper funtions to AudioRecording model: a split hash function that reliably splits the hash protocol from the hash value; and a canonical filename function that can generate ideal storage names for audio recordings
- Also fixes `original_file_paths` and `original_format_calculated` methods on AudioRecording
- Adds support to range request for configuring download names and content disposition types
- Patches acceptance spec helper so that large binary blobs are not printed when tests fail
> Adds support downloading original audio files

- lib/modules/api/media_metadata.rb
- spec/acceptance/media_spec.rb
In the API response to json request for media, when filtering available formats to only include formats that support the specified sample rate, native sample rate is used if no sample rate is specified in request parameters.
That is, if no sample rate is specified in the request, available formats will only include those that support the native sample rate.
The actual change to `api_response` is really small, but, due to subsequent references to `available` for the options, this change meant rearranging the method quite a bit. 
Added one extra test within and existing example.
> Default to native sample rate when filtering out invalid available

- app/controllers/application_controller.rb
- app/controllers/dataset_items_controller.rb
- app/controllers/progress_events_controller.rb
- lib/modules/api/response.rb
- spec/requests/dataset_items_spec.rb
- spec/requests/projects_spec.rb
Fixes #366. Fixes #361.
If there are no params, determines whether the request body was empty or if it just was not parsed properly, and responds with approprtiate error code depending on the situation.
If the body was empty, includes an error link to the new action.
If the body was not empty, responds with unsupported_media_type.
> Checks that post params is not empty for update and create

- app/controllers/dataset_items_controller.rb
- app/controllers/progress_events_controller.rb
- app/models/ability.rb
- app/models/dataset.rb
- app/models/dataset_item.rb
- app/models/progress_event.rb
- config/routes.rb
- lib/modules/access/by_permission.rb
- lib/modules/api/response.rb
- lib/modules/filter/query.rb
- lib/modules/filter/validate.rb
- spec/acceptance/audio_events_spec.rb
- spec/acceptance/dataset_items_spec.rb
- spec/acceptance/progress_events_spec.rb
- spec/acceptance/projects_spec.rb
- spec/factories/dataset_item_factory.rb
- spec/lib/creation.rb
- spec/lib/creation_spec.rb
- spec/requests/dataset_items_spec.rb
- spec/requests/datasets_spec.rb
- spec/requests/progress_events_spec.rb
- spec/routing/progress_events_routing_spec.rb
Closes #371 
Fixes #368
(Included filter specs that return datasets that have different audio_recording_ids in the correct order)
Closes #348
Progress events api endpoints. The standard endpoints plus:
- a specific endpoint in dataset items controller #filter_todo that performs the filter with a priority algorithm that returns dataset items in order of their count of 'viewed' progress events.  It was named 'filter_todo' because it returns items in a dataset that are still "to do", i.e. they have not yet been viewed. I am happy for this to be replaced with a better name. 
- a specific endpoint for adding progress events with route parameters that define the parent dataset_item by its dataset_id, audio_recording_id, start_time_seconds, and end_time_seconds. This endpoint allows adding of …
> Feature progress events endpoints

- app/views/audio_events/download.csv.erb
- spec/requests/audio_events_spec.rb
> removed leading space in csv column header names

- .rubocop.yml
- app/controllers/sites_controller.rb
- app/models/site.rb
- app/models/user.rb
- lib/modules/api/image.rb
- spec/acceptance/sites_spec.rb
- spec/models/site_spec.rb
Updated the `filter_settings` output of the sites model
- Extracted image_urls from User model into `Api::Image.image_urls` so that it is reusable for other models
- Updated document formatting to be compatible with rubocop for some files
- Added model output checking for INDEX site route
- Modified `filter_settings` for Site model
Closes #453
> Missing site model details

- .rubocop.yml
- .vscode/tasks.json
- app/controllers/admin/tags_controller.rb
- app/controllers/application_controller.rb
- app/controllers/tags_controller.rb
- app/models/tag.rb
- db/migrate/20200612004608_change_tag_notes_to_json.rb
- db/structure.sql
- spec/acceptance/tags_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/factories/tag_factory.rb
- spec/helpers/creation.rb
- spec/helpers/migrations_helper.rb
- spec/migrations/change_tag_notes_to_json_spec.rb
- spec/models/tag_spec.rb
- spec/rails_helper.rb
- spec/requests/tags_spec.rb
Minor modifications to the tag model, table, and API.
- Updated the tag model to expose the following properties:
- `notes`
- `creator_id`
- `updater_id`
- `created_at`
- `updated_at`
```JSON
{
"id": 1,
"text": "test tag #1",
"is_taxanomic": false,
"type_of_tag": "general",
"retired": false,
"notes": null,
"creator_id": 1,
"updater_id": null,
"created_at": "2020-06-22T13:30:37.832+10:00",
"updated_at": "2020-06-22T13:30:37.832+10:00"
}
```
- Modified tags table to change notes column from type `Text` to `JsonB`. Following migration cases were tested manually:
|          test           |              before            |                      after                      |
|-------------------------|----------------------------------|-------------------------------------------------|
| null …
> Missing tag model details

- app/controllers/analysis_jobs_controller.rb
- app/controllers/audio_event_comments_controller.rb
- app/controllers/audio_events_controller.rb
- app/controllers/dataset_items_controller.rb
- app/controllers/progress_events_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/public_controller.rb
- app/controllers/responses_controller.rb
- app/controllers/sites_controller.rb
- app/controllers/taggings_controller.rb
- app/modules/access/by_permission.rb
- app/modules/api/analysis_jobs_items_shared.rb
- spec/lib/modules/filter/query_spec.rb
- spec/models/analysis_jobs_item_spec.rb
Modified `Access::ByPermission` functions to utilise keyword arguments instead of positional arguments for default values.
> By permission keyword arguments

- app/controllers/regions_controller.rb
- app/controllers/sites_controller.rb
- app/models/ability.rb
- app/models/project.rb
- app/models/region.rb
- app/models/site.rb
- app/models/user.rb
- app/modules/access/by_permission.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- config/routes.rb
- config/storage.yml
- db/migrate/20200831130746_create_active_storage_tables.active_storage.rb
- db/migrate/20200901011916_create_regions.rb
- db/structure.sql
- spec/api/regions_spec.rb
- spec/factories/region_factory.rb
- spec/helpers/creation.rb
- spec/helpers/factory_bot_helpers.rb
- spec/helpers/permissions_helper.rb
- spec/models/project_spec.rb
- spec/models/region_spec.rb
- spec/models/site_spec.rb
- spec/models/user_spec.rb
- spec/requests/permissions/regions_spec.rb
- spec/swagger_helper.rb
- spec/unit/active_storage.rb
Closes #383
In an ideal world our 'sites' table would be named 'points' and if we had sites they would represent an area/region of study where several sensors were deployed as points.
However, we do have a concept of a point named with the term 'site'. Correcting this mistake is prohibitively expensive.
Instead we know introduce the concept of a region. A region is an area of study, usually small, where a group of related sensors are deployed as 'sites'. A region as introduced here is consistent with the ecological definition of a site.
We also desperately wanted to avoid changing the hierarchy in the app - especially with all the complexities involved with sites<->projects. So this means it is optional for a site to belong to a region.
This idea was previously named site_groups because …
> Adds regions and active storage

- .rubocop.yml
- Gemfile
- app/controllers/public_controller.rb
- app/controllers/stats_controller.rb
- app/models/application_record.rb
- app/models/audio_event.rb
- app/models/audio_recording.rb
- app/models/user.rb
- app/modules/timestamp_helpers.rb
- config/routes.rb
- spec/api/stats_spec.rb
- spec/models/audio_event_spec.rb
- spec/models/audio_recording_spec.rb
- spec/models/user_spec.rb
- spec/requests/permissions/stats_spec.rb
- spec/requests/permissions/status_spec.rb
- spec/requests/stats_spec.rb
- spec/routing/stats_routing_spec.rb
- spec/swagger_helper.rb
Fixes #523,  Closes #413
Factored stats out into it's own controller for neatness.
Had to maintain backwards compatibility with old website_status view, but it should be easy enough to rip that out later.
Added some generic scopes to any model that implements the timestamps protocol.
Removed all raw SQL from the stats queries.
N/A
N/A
> Fixes stats page and adds stats endpoint

- app/models/audio_recording.rb
- app/models/current.rb
- app/modules/api/controller_helper.rb
- app/modules/api/response.rb
- app/modules/api/schema.rb
- app/modules/filter/query.rb
- app/modules/filter/validate.rb
- app/modules/set_current.rb
- spec/acceptance/datasets_spec.rb
- spec/acceptance/media/media_original_spec.rb
- spec/helpers/capabilities_helper.rb
- spec/helpers/request_spec_helpers.rb
- spec/helpers/shared_context/api_spec_shared_context.rb
- spec/helpers/shared_examples/capabilities_for.rb
- spec/helpers/solargraph.rb
- spec/rails_helper.rb
- spec/requests/capabilities/README.md
- spec/requests/capabilities/audio_recordings_spec.rb
- spec/requests/permissions/projects_spec.rb
- swagger/v2/swagger.yaml
#Also adds a basic capabilities framework.
Closes #551
Closes #491
Adds a basic capabilities framework, in accordance with https://github.com/QutEcoacoustics/baw-server/wiki/API:-Capabilties
- Added a basic capabilities framework
- Added the original download capability for audio recordings
The plan was for:
- basic capabilities (get, post, put, patch, delete, etc..) to be included with every resource but that is being left for later
- the spec also defined capabilities as being opt-in which is also not completed here
- more work than required for MVP
- also not sure if it is the right choice
N/A
- [ x Assign reviewers if you have permission
> Adds original download capability

- app/controllers/sessions_controller.rb
- app/modules/set_current.rb
- spec/controllers/application_controller_spec.rb
I had assumed that current_ability would not be set to a useful value when current_user was nil. Actually though, CanCanCan does provide a useful ability instance even when a user is nil and I should not have not set Current.ability when current_user was nil.
Fixes #553
Adds more tests for the current class and also fixes aforementioned bug.
N/A
N/A
> Fixes Current.ability

- app/controllers/projects_controller.rb
- app/models/project.rb
- db/migrate/20240110141130_add_license_to_projects.rb
- db/structure.sql
- spec/factories/project_factory.rb
- spec/models/project_spec.rb
- spec/requests/projects_spec.rb
Given that projects can be publically available for viewing, users have commonly associated usage rights and licensing information with the projects. However, with existing API capabilities, this information is usually encoded in the `description` field.
The addition of a specific `license` attribute on projects will allow uses to either: Reference an SPDX license code or insert a custom license as free form text.
- Adds a license filed to project models
Fixes: #289 
None
None
> Add nullable license field to Projects model

- app/controllers/sites_controller.rb
- app/models/site.rb
- spec/factories/site_factory.rb
- spec/models/site_spec.rb
- spec/requests/sites_spec.rb
- spec/requests/stats_spec.rb
- spec/support/creation_helper.rb
Fixes #679
`<<` instantly saves the added association. We were adding the project from the route parameter onto the site object temporarily, assuming the site would not be saved.
Instead whenever the route was accessed with any project id, that project id was added to the list of available projects - creating an security bypass.
I also took this opportunity to disallow the creation of new sites that belong to multiple projects. It is a feature we plan to remove anyway.
We still have to allow updating multi-project sites - at least until we can ensure there are no examples of them in the database.
> Fixes multiple assignment bug

- lib/gems/baw-workers/lib/baw_workers/active_job/recurring.rb
- lib/gems/baw-workers/lib/baw_workers/jobs/analysis/remote_stale_check_job.rb
- lib/gems/baw-workers/lib/baw_workers/resque_api.rb
- spec/lib/gems/baw_workers/jobs/analysis/remote_stale_check_job_spec.rb
Our remote stale job was not enqueuing correctly from the scheduler. This is because we had no way to supply arguments to scheduled jobs and my own silly job argument validator could not handle that.
Before:
After:
> Fix stale job scheduling

- baw-server.code-workspace
- lib/gems/baw-audio-tools/lib/baw_audio_tools/run_external_program.rb
- lib/gems/baw-workers/lib/baw_workers/jobs/harvest/harvest_job.rb
- lib/gems/baw-workers/lib/baw_workers/jobs/harvest/validations.rb
- spec/fixtures/fixtures.rb
- spec/lib/gems/baw_audio_tools/run_external_program_spec.rb
- spec/lib/gems/baw_workers/jobs/harvest/edge_cases/mixed_encoding_filenames_spec.rb
- spec/rails_helper.rb
- spec/support/matchers/string_to_have_encoding.rb
The harvester now rejects files that have control characters in their filename or invalid utf-8 sequences.
Program runner is also more resilient to parsing invalid characters.
Fixes #702
> Make harvester more resilient to bad paths

- app/models/audio_event.rb
- spec/models/audio_event_spec.rb
Fixes: #762
- Emits `score` from model returned from api
- Adds `score` as a required field on the audio_event model
- API docs have not been updated
> Emit score field from audio event responses

- app/modules/api/response.rb
- app/modules/include_controller.rb
- spec/README.md
- spec/lib/modules/filter/query_spec.rb
- spec/requests/application_spec.rb
- spec/requests/verifications_spec.rb
Database conflict errors will include the keys/values of rows with the unique constraint violation. This will benefit graceful error handling on the front-end.  
- utilising the existing `error_info` object to return a hash `unique_violation` containing key value pairs for conflicting rows
- update test in verifications_spec
- expect_error still passes when using info=nil (default), preserving existing test behaviour
- unrelated in `app/modules/api/response.rb:242` bugfix? as symbol always evaluates to true
None identified
> # Improve database conflict error messages

- baw-server.code-workspace
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_base.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_ffmpeg.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_mp3splt.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_shntool.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_sox.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_wac2wav.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/audio_wavpack.rb
- lib/gems/baw-audio-tools/lib/baw_audio_tools/image_image_magick.rb
- lib/gems/emu/lib/emu.rb
- spec/lib/gems/baw_audio_tools/audio_ffmpeg_spec.rb
- spec/lib/gems/baw_audio_tools/audio_wac2wav_spec.rb
- spec/lib/gems/baw_workers/jobs/harvest/edge_cases/dollar_in_filename_spec.rb
- spec/lib/gems/emu/emu_spec.rb
- spec/support/stepwise/stepwise.rb
Uses single quotes to escape paths to executables
Fixes https://github.com/QutEcoacoustics/baw-server/issues/825.
We should be able to process files that have, e.g. `$` symbols in them now
> Fix quoting
